fixup! simplify

diff --git a/bin/stack2cabal b/bin/stack2cabal
--- a/bin/stack2cabal
+++ b/bin/stack2cabal
@@ -3,10 +3,21 @@
 # invokes hpack and stackage-to-hackage producing cabal.project,
 # cabal.project.freeze and *.cabal files.
 
-# TODO: rewrite as a Haskell app and release on Hackage
+# TODO: rewrite this script as a Haskell app and release on Hackage, depending
+# on hpack and stackage-to-hackage as library deps.
 
 if [ ! -f stack.yaml ] ; then
-    echo "No stack.yaml in $PWD"
+    echo "ERROR: stack.yaml does not exist in $PWD"
+    exit 1
+fi
+
+if [ -z "$(which hpack 2>/dev/null)" ] ; then
+    echo "ERROR: hpack is not installed, try: cabal v2-install hpack"
+    exit 1
+fi
+
+if [ -z "$(which stackage-to-hackage 2>/dev/null)" ] ; then
+    echo "ERROR: stackage-to-hackage is not installed, try: cabal v2-install stackage-to-hackage"
     exit 1
 fi
 
